name: fnx_ui
description: Desktop first components from Angular2 Dart.
version: 0.1.6
author: Tomucha <tomucha@gmail.com>
#homepage: https://www.example.com

environment:
  sdk: '^2.10.0'

dependencies:
  angular: ^6.0.1
  angular_forms: ^3.0.0
  angular_router: ^2.0.0-alpha+22
  logging: any
  intl: any
  cooky: any

dev_dependencies:
  build_runner: ">=1.6.2 <2.0.0"
  build_test: any
  build_web_compilers: ">=2.12.0 <3.0.0"
  test: any