name: fnx_ui
description: Desktop first components from Angular2 Dart.
version: 0.1.6
author: Tomucha <tomucha@gmail.com>
#homepage: https://www.example.com

environment:
  sdk: '^2.0.0'

dependencies:
  angular: ^5.0.0
  angular_forms: ^2.0.0
  angular_router: ^2.0.0-alpha+19
  logging: "^0.11.3"
  intl: any
  cooky: any

dev_dependencies:
  build_runner: ^0.9.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.3.0
  intl_translation: any
