name: fnx_ui
description: Desktop first components from Angular2 Dart.
version: 0.2.0
author: Tomucha <tomucha@gmail.com>
#homepage: https://www.example.com

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  angular: ^7.0.2
  angular_forms: ^4.0.1
  angular_router: ^3.0.1
  logging: any
  intl: any
  cooky: any
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  build_runner: ^2.1.5
  build_test: any
  build_web_compilers: ^3.2.1
  test: any
