name: 'fnx_ui'
version: 0.0.1
description: A web app built using polymer.dart.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  browser: ^0.10.0
  polymer: ^1.0.0-rc.2
  reflectable: ^0.3.1
  web_components: ^0.12.0
  less_dart: any
  polymer_elements: ^1.0.0-rc.1
  fnx_router: any
  logging: any

transformers:
- less_dart:
    compress: true
    silent: false
    include_path: lib
- web_components:
    entry_points:
      - web/index.html
      - web/paper-routing.html
- reflectable:
    entry_points: web/index.dart
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
