name: fnx_ui_showcase
description: Desktop first components from Angular2 Dart - showcase
version: 0.2.0
author: Tomucha <tomucha@gmail.com>
#homepage: https://www.example.com

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  angular: any
  fnx_ui:
    path: ../fnx_ui/

dev_dependencies:
  build_runner: ^2.1.5
  build_web_compilers: ^3.2.1