name: fnx_ui_showcase
description: Desktop first components from Angular2 Dart - showcase
version: 0.0.1
author: Tomucha <tomucha@gmail.com>
#homepage: https://www.example.com

environment:
  sdk: '^2.0.0'

dependencies:
  angular: ^5.0.0
  fnx_ui:
    path: ../fnx_ui/

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^0.9.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
