name: fnx_ui_showcase
description: Desktop first components from Angular2 Dart - showcase
version: 0.0.1
author: Tomucha <tomucha@gmail.com>
#homepage: https://www.example.com

environment:
  sdk: '^2.1.0'

dependencies:
  angular: ^5.1.0
  fnx_ui:
    path: ../fnx_ui/

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ">2.6.0"
